<a href="https://colab.research.google.com/github/Sakhiur2022/QSAR-modeling-for-DHFR-TS/blob/main/Descriptor_Dataset_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Bioinformatics Project - Computational Drug Discovery [Part 3] Descriptor Calculation and Dataset Preparation**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

In **Part 3**, we will be calculating molecular descriptors that are essentially quantitative description of the compounds in the dataset. Finally, we will be preparing this into a dataset for subsequent model building in Part 4.

---

## **Download PaDEL-Descriptor**

### **New version**

In [ ]:
! pip install padelpy

Collecting padelpy
  Downloading padelpy-0.1.16-py3-none-any.whl.metadata (7.7 kB)
Downloading padelpy-0.1.16-py3-none-any.whl (20.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 95.3 MB/s eta 0:00:00
Installing collected packages: padelpy
Successfully installed padelpy-0.1.16

## **Load bioactivity data**

Download the curated ChEMBL bioactivity data that has been pre-processed from Parts 1 and 2 of this Bioinformatics Project series. Here we will be using the **bioactivity_data_3class_pIC50.csv** file that essentially contain the pIC50 values that we will be using for building a regression model.

In [ ]:
! wget https://raw.githubusercontent.com/dataprofessor/data/master/acetylcholinesterase_04_bioactivity_data_3class_pIC50.csv

--2026-06-07 16:44:46--  https://raw.githubusercontent.com/dataprofessor/data/master/acetylcholinesterase_04_bioactivity_data_3class_pIC50.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 655414 (640K) [text/plain]
Saving to: ‘acetylcholinesterase_04_bioactivity_data_3class_pIC50.csv’

acetylcholinesteras 100%[===================>] 640.05K  --.-KB/s    in 0.05s

2026-06-07 16:44:46 (13.6 MB/s) - ‘acetylcholinesterase_04_bioactivity_data_3class_pIC50.csv’ saved [655414/655414]

In [ ]:
import pandas as pd

In [ ]:
df3 = pd.read_csv('acetylcholinesterase_04_bioactivity_data_3class_pIC50.csv')

In [ ]:
df3

,Unnamed: 0,molecule_chembl_id,canonical_smiles,class,MW,LogP,NumHDonors,NumHAcceptors,pIC50
0,0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,active,312.325,2.80320,0.0,6.0,6.124939
1,1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,active,376.913,4.55460,0.0,5.0,7.000000
2,2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,inactive,426.851,5.35740,0.0,5.0,4.301030
3,3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,active,404.845,4.70690,0.0,5.0,6.522879
4,4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,active,346.334,3.09530,0.0,6.0,6.096910
...,...,...,...,...,...,...,...,...,...
4690,4690,CHEMBL4293155,CC(C)(C)c1cc(/C=C/C(=O)NCCC2CCN(Cc3ccccc3Cl)CC...,intermediate,511.150,7.07230,2.0,3.0,5.612610
4691,4691,CHEMBL4282558,CC(C)(C)c1cc(/C=C/C(=O)NCCC2CCN(Cc3cccc(Cl)c3)...,intermediate,511.150,7.07230,2.0,3.0,5.595166
4692,4692,CHEMBL4281727,CC(C)(C)c1cc(/C=C/C(=O)NCCC2CCN(Cc3ccc(Br)cc3)...,intermediate,555.601,7.18140,2.0,3.0,5.419075
4693,4693,CHEMBL4292349,CC(C)(C)c1cc(/C=C/C(=O)NCCC2CCN(Cc3cccc([N+](=...,intermediate,521.702,6.32710,2.0,5.0,5.460924
4694,4694,CHEMBL4278260,CC(C)(C)c1cc(/C=C/C(=O)NCCC2CCN(Cc3ccc(C#N)cc3...,intermediate,501.715,6.29058,2.0,4.0,5.555955

In [ ]:
selection = ['canonical_smiles','molecule_chembl_id']
df3_selection = df3[selection]
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [ ]:
! cat molecule.smi | head -5

CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1	CHEMBL133897
O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1	CHEMBL336398
CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1	CHEMBL131588
O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F	CHEMBL130628
CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C	CHEMBL130478

In [ ]:
! cat molecule.smi | wc -l

4695

## **Calculate fingerprint descriptors**

### **Calculate PaDEL descriptors (Depricated)**

In [ ]:
! cat padel.sh

java -Xms1G -Xmx1G -Djava.awt.headless=true -jar ./PaDEL-Descriptor/PaDEL-Descriptor.jar -removesalt -standardizenitro -fingerprints -descriptortypes ./PaDEL-Descriptor/PubchemFingerprinter.xml -dir ./ -file descriptors_output.csv

In [ ]:
! bash padel.sh

Processing CHEMBL133897 in molecule.smi (1/4695).
Processing CHEMBL336398 in molecule.smi (2/4695).
Processing CHEMBL130628 in molecule.smi (4/4695). Average speed: 2.98 s/mol.
Processing CHEMBL131588 in molecule.smi (3/4695). Average speed: 5.85 s/mol.
Processing CHEMBL130478 in molecule.smi (5/4695). Average speed: 2.15 s/mol.
Processing CHEMBL130098 in molecule.smi (7/4695). Average speed: 1.40 s/mol.
Processing CHEMBL130112 in molecule.smi (6/4695). Average speed: 1.71 s/mol.
Processing CHEMBL337486 in molecule.smi (8/4695). Average speed: 1.25 s/mol.
Processing CHEMBL336538 in molecule.smi (9/4695). Average speed: 1.08 s/mol.
Processing CHEMBL131051 in molecule.smi (10/4695). Average speed: 1.01 s/mol.
Processing CHEMBL341437 in molecule.smi (11/4695). Average speed: 0.93 s/mol.
Processing CHEMBL335033 in molecule.smi (12/4695). Average speed: 0.88 s/mol.
Processing CHEMBL122983 in molecule.smi (13/4695). Average speed: 0.90 s/mol.
Processing CHEMBL338720 in molecule.smi (14/4695). Average speed: 0.80 s/mol.
Processing CHEMBL339995 in molecule.smi (15/4695). Average speed: 0.79 s/mol.
Processing CHEMBL131536 in molecule.smi (17/4695). Average speed: 0.71 s/mol.
Processing CHEMBL335158 in molecule.smi (16/4695). Average speed: 0.75 s/mol.
Processing CHEMBL106126 in molecule.smi (18/4695). Average speed: 0.70 s/mol.
Processing CHEMBL336625 in molecule.smi (20/4695). Average speed: 0.64 s/mol.
Processing CHEMBL334971 in molecule.smi (19/4695). Average speed: 0.68 s/mol.
Processing CHEMBL130666 in molecule.smi (21/4695). Average speed: 0.66 s/mol.
Processing CHEMBL134061 in molecule.smi (22/4695). Average speed: 0.63 s/mol.
Processing CHEMBL133388 in molecule.smi (23/4695). Average speed: 0.62 s/mol.
Processing CHEMBL130645 in molecule.smi (24/4695). Average speed: 0.60 s/mol.
Processing CHEMBL133580 in molecule.smi (25/4695). Average speed: 0.59 s/mol.
Processing CHEMBL336524 in molecule.smi (26/4695). Average speed: 0.57 s/mol.
Processing CHEMBL336276 in molecule.smi (27/4695). Average speed: 0.56 s/mol.
Processing CHEMBL334395 in molecule.smi (28/4695). Average speed: 0.56 s/mol.
Processing CHEMBL131320 in molecule.smi (29/4695). Average speed: 0.54 s/mol.
Processing CHEMBL339297 in molecule.smi (30/4695). Average speed: 0.53 s/mol.
Processing CHEMBL337714 in molecule.smi (31/4695). Average speed: 0.52 s/mol.
Processing CHEMBL122575 in molecule.smi (32/4695). Average speed: 0.51 s/mol.
Processing CHEMBL130704 in molecule.smi (33/4695). Average speed: 0.51 s/mol.
Processing CHEMBL46151 in molecule.smi (34/4695). Average speed: 0.50 s/mol.
Processing CHEMBL54126 in molecule.smi (35/4695). Average speed: 0.49 s/mol.
Processing CHEMBL297316 in molecule.smi (36/4695). Average speed: 0.48 s/mol.
Processing CHEMBL65667 in molecule.smi (37/4695). Average speed: 0.47 s/mol.
Processing CHEMBL431519 in molecule.smi (38/4695). Average speed: 0.46 s/mol.
Processing CHEMBL296429 in molecule.smi (39/4695). Average speed: 0.46 s/mol.
Processing CHEMBL154972 in molecule.smi (40/4695). Average speed: 0.45 s/mol.
Processing CHEMBL152722 in molecule.smi (41/4695). Average speed: 0.45 s/mol.
Processing CHEMBL544022 in molecule.smi (42/4695). Average speed: 0.45 s/mol.
Processing CHEMBL349127 in molecule.smi (43/4695). Average speed: 0.44 s/mol.
Processing CHEMBL156659 in molecule.smi (44/4695). Average speed: 0.44 s/mol.
Processing CHEMBL45118 in molecule.smi (45/4695). Average speed: 0.43 s/mol.
Processing CHEMBL155322 in molecule.smi (47/4695). Average speed: 0.42 s/mol.
Processing CHEMBL542609 in molecule.smi (46/4695). Average speed: 0.43 s/mol.
Processing CHEMBL1203537 in molecule.smi (49/4695). Average speed: 0.41 s/mol.
Processing CHEMBL154211 in molecule.smi (48/4695). Average speed: 0.42 s/mol.
Processing CHEMBL86 in molecule.smi (50/4695). Average speed: 0.41 s/mol.
Processing CHEMBL47375 in molecule.smi (51/4695). Average speed: 0.41 s/mol.
Processing CHEMBL542360 in molecule.smi (52/4695). Average speed: 0.40 s/mol.
Processing CHEMBL345849 in molecule.smi (53/4695). Average speed: 0.41 s/mol.
Processing CHEMBL154689 in molecule.smi (54/4695). Average speed: 0.39 s/mol.
Processing CHEMBL346733 in molecule.smi (55/4695). Average speed: 0.39 s/mol.
Processing CHEMBL416464 in molecule.smi (56/4695). Average speed: 0.39 s/mol.
Processing CHEMBL1203539 in molecule.smi (57/4695). Average speed: 0.38 s/mol.
Processing CHEMBL347729 in molecule.smi (58/4695). Average speed: 0.38 s/mol.
Processing CHEMBL63173 in molecule.smi (60/4695). Average speed: 0.37 s/mol.
Processing CHEMBL296786 in molecule.smi (59/4695). Average speed: 0.37 s/mol.
Processing CHEMBL292788 in molecule.smi (62/4695). Average speed: 0.37 s/mol.
Processing CHEMBL433041 in molecule.smi (61/4695). Average speed: 0.37 s/mol.
Processing CHEMBL155392 in molecule.smi (64/4695). Average speed: 0.37 s/mol.
Processing CHEMBL33051 in molecule.smi (63/4695). Average speed: 0.37 s/mol.
Processing CHEMBL543546 in molecule.smi (66/4695). Average speed: 0.36 s/mol.
Processing CHEMBL153311 in molecule.smi (65/4695). Average speed: 0.36 s/mol.
Processing CHEMBL556172 in molecule.smi (68/4695). Average speed: 0.35 s/mol.
Processing CHEMBL1420 in molecule.smi (67/4695). Average speed: 0.36 s/mol.
Processing CHEMBL154263 in molecule.smi (69/4695). Average speed: 0.35 s/mol.
Processing CHEMBL544669 in molecule.smi (70/4695). Average speed: 0.34 s/mol.
Processing CHEMBL62664 in molecule.smi (71/4695). Average speed: 0.35 s/mol.
Processing CHEMBL155111 in molecule.smi (72/4695). Average speed: 0.34 s/mol.
Processing CHEMBL1203534 in molecule.smi (73/4695). Average speed: 0.34 s/mol.
Processing CHEMBL541044 in molecule.smi (74/4695). Average speed: 0.34 s/mol.
Processing CHEMBL543779 in molecule.smi (75/4695). Average speed: 0.33 s/mol.
Processing CHEMBL155495 in molecule.smi (76/4695). Average speed: 0.33 s/mol.
Processing CHEMBL64011 in molecule.smi (77/4695). Average speed: 0.33 s/mol.
Processing CHEMBL65585 in molecule.smi (78/4695). Average speed: 0.33 s/mol.
Processing CHEMBL347539 in molecule.smi (79/4695). Average speed: 0.33 s/mol.
Processing CHEMBL154433 in molecule.smi (80/4695). Average speed: 0.33 s/mol.
Processing CHEMBL157208 in molecule.smi (81/4695). Average speed: 0.32 s/mol.
Processing CHEMBL1790041 in molecule.smi (82/4695). Average speed: 0.32 s/mol.
Processing CHEMBL65356 in molecule.smi (83/4695). Average speed: 0.32 s/mol.
Processing CHEMBL154366 in molecule.smi (84/4695). Average speed: 0.32 s/mol.
Processing CHEMBL153821 in molecule.smi (85/4695). Average speed: 0.32 s/mol.
Processing CHEMBL416644 in molecule.smi (86/4695). Average speed: 0.31 s/mol.
Processing CHEMBL94 in molecule.smi (87/4695). Average speed: 0.31 s/mol.
Processing CHEMBL303574 in molecule.smi (88/4695). Average speed: 0.31 s/mol.
Processing CHEMBL296277 in molecule.smi (90/4695). Average speed: 0.31 s/mol.
Processing CHEMBL65018 in molecule.smi (89/4695). Average speed: 0.31 s/mol.
Processing CHEMBL1203535 in molecule.smi (92/4695). Average speed: 0.30 s/mol.
Processing CHEMBL66309 in molecule.smi (91/4695). Average speed: 0.31 s/mol.
Processing CHEMBL296560 in molecule.smi (93/4695). Average speed: 0.31 s/mol.
Processing CHEMBL152260 in molecule.smi (94/4695). Average speed: 0.30 s/mol.
Processing CHEMBL296669 in molecule.smi (96/4695). Average speed: 0.30 s/mol.
Processing CHEMBL154950 in molecule.smi (95/4695). Average speed: 0.30 s/mol.
Processing CHEMBL1203538 in molecule.smi (97/4695). Average speed: 0.30 s/mol.
Processing CHEMBL19060 in molecule.smi (98/4695). Average speed: 0.29 s/mol.
Processing CHEMBL422977 in molecule.smi (99/4695). Average speed: 0.29 s/mol.
Processing CHEMBL11805 in molecule.smi (100/4695). Average speed: 0.30 s/mol.
Processing CHEMBL302179 in molecule.smi (101/4695). Average speed: 0.30 s/mol.
Processing CHEMBL27673 in molecule.smi (102/4695). Average speed: 0.30 s/mol.
Processing CHEMBL132377 in molecule.smi (103/4695). Average speed: 0.30 s/mol.
Processing CHEMBL132133 in molecule.smi (104/4695). Average speed: 0.30 s/mol.
Processing CHEMBL95 in molecule.smi (105/4695). Average speed: 0.30 s/mol.
Processing CHEMBL134488 in molecule.smi (106/4695). Average speed: 0.30 s/mol.
Processing CHEMBL134382 in molecule.smi (107/4695). Average speed: 0.30 s/mol.
Processing CHEMBL59109 in molecule.smi (108/4695). Average speed: 0.30 s/mol.
Processing CHEMBL286990 in molecule.smi (109/4695). Average speed: 0.30 s/mol.
Processing CHEMBL294891 in molecule.smi (110/4695). Average speed: 0.30 s/mol.
Processing CHEMBL1255901 in molecule.smi (111/4695). Average speed: 0.29 s/mol.
Processing CHEMBL89011 in molecule.smi (112/4695). Average speed: 0.29 s/mol.
Processing CHEMBL748 in molecule.smi (113/4695). Average speed: 0.29 s/mol.
Processing CHEMBL29300 in molecule.smi (115/4695). Average speed: 0.29 s/mol.
Processing CHEMBL50608 in molecule.smi (114/4695). Average speed: 0.29 s/mol.
Processing CHEMBL27675 in molecule.smi (116/4695). Average speed: 0.29 s/mol.
Processing CHEMBL60167 in molecule.smi (118/4695). Average speed: 0.28 s/mol.
Processing CHEMBL435373 in molecule.smi (117/4695). Average speed: 0.29 s/mol.
Processing CHEMBL314800 in molecule.smi (120/4695). Average speed: 0.28 s/mol.
Processing CHEMBL89012 in molecule.smi (119/4695). Average speed: 0.28 s/mol.
Processing CHEMBL553212 in molecule.smi (121/4695). Average speed: 0.28 s/mol.
Processing CHEMBL156630 in molecule.smi (122/4695). Average speed: 0.28 s/mol.
Processing CHEMBL315013 in molecule.smi (123/4695). Average speed: 0.28 s/mol.
Processing CHEMBL155754 in molecule.smi (124/4695). Average speed: 0.28 s/mol.
Processing CHEMBL314658 in molecule.smi (125/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87170 in molecule.smi (126/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87959 in molecule.smi (127/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87295 in molecule.smi (128/4695). Average speed: 0.28 s/mol.
Processing CHEMBL82810 in molecule.smi (129/4695). Average speed: 0.28 s/mol.
Processing CHEMBL157182 in molecule.smi (130/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87128 in molecule.smi (132/4695). Average speed: 0.28 s/mol.
Processing CHEMBL88049 in molecule.smi (131/4695). Average speed: 0.28 s/mol.
Processing CHEMBL160219 in molecule.smi (133/4695). Average speed: 0.28 s/mol.
Processing CHEMBL85473 in molecule.smi (135/4695). Average speed: 0.28 s/mol.
Processing CHEMBL445916 in molecule.smi (134/4695). Average speed: 0.28 s/mol.
Processing CHEMBL314502 in molecule.smi (136/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87320 in molecule.smi (137/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87280 in molecule.smi (138/4695). Average speed: 0.28 s/mol.
Processing CHEMBL348607 in molecule.smi (139/4695). Average speed: 0.28 s/mol.
Processing CHEMBL313809 in molecule.smi (140/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87849 in molecule.smi (141/4695). Average speed: 0.28 s/mol.
Processing CHEMBL314398 in molecule.smi (142/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87373 in molecule.smi (143/4695). Average speed: 0.28 s/mol.
Processing CHEMBL156931 in molecule.smi (144/4695). Average speed: 0.28 s/mol.
Processing CHEMBL83005 in molecule.smi (145/4695). Average speed: 0.28 s/mol.
Processing CHEMBL315515 in molecule.smi (146/4695). Average speed: 0.28 s/mol.
Processing CHEMBL441632 in molecule.smi (147/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87937 in molecule.smi (148/4695). Average speed: 0.28 s/mol.
Processing CHEMBL441808 in molecule.smi (149/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87649 in molecule.smi (150/4695). Average speed: 0.28 s/mol.
Processing CHEMBL160836 in molecule.smi (151/4695). Average speed: 0.28 s/mol.
Processing CHEMBL156861 in molecule.smi (152/4695). Average speed: 0.28 s/mol.
Processing CHEMBL314766 in molecule.smi (153/4695). Average speed: 0.28 s/mol.
Processing CHEMBL88026 in molecule.smi (154/4695). Average speed: 0.28 s/mol.
Processing CHEMBL86233 in molecule.smi (155/4695). Average speed: 0.28 s/mol.
Processing CHEMBL155350 in molecule.smi (156/4695). Average speed: 0.28 s/mol.
Processing CHEMBL155863 in molecule.smi (157/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87980 in molecule.smi (158/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87441 in molecule.smi (159/4695). Average speed: 0.28 s/mol.
Processing CHEMBL158946 in molecule.smi (160/4695). Average speed: 0.28 s/mol.
Processing CHEMBL87550 in molecule.smi (161/4695). Average speed: 0.28 s/mol.
Processing CHEMBL609440 in molecule.smi (162/4695). Average speed: 0.28 s/mol.
Processing CHEMBL313271 in molecule.smi (164/4695). Average speed: 0.28 s/mol.
Processing CHEMBL350464 in molecule.smi (163/4695). Average speed: 0.28 s/mol.
Processing CHEMBL423313 in molecule.smi (165/4695). Average speed: 0.28 s/mol.
Processing CHEMBL309667 in molecule.smi (166/4695). Average speed: 0.28 s/mol.
Processing CHEMBL419470 in molecule.smi (167/4695). Average speed: 0.28 s/mol.
Processing CHEMBL80221 in molecule.smi (168/4695). Average speed: 0.28 s/mol.
Processing CHEMBL431844 in molecule.smi (169/4695). Average speed: 0.28 s/mol.
Processing CHEMBL80247 in molecule.smi (170/4695). Average speed: 0.27 s/mol.
Processing CHEMBL77896 in molecule.smi (172/4695). Average speed: 0.27 s/mol.
Processing CHEMBL418917 in molecule.smi (171/4695). Average speed: 0.27 s/mol.
Processing CHEMBL369661 in molecule.smi (173/4695). Average speed: 0.27 s/mol.
Processing CHEMBL74089 in molecule.smi (175/4695). Average speed: 0.27 s/mol.
Processing CHEMBL502 in molecule.smi (174/4695). Average speed: 0.27 s/mol.
Processing CHEMBL134057 in molecule.smi (176/4695). Average speed: 0.27 s/mol.
Processing CHEMBL76640 in molecule.smi (177/4695). Average speed: 0.27 s/mol.
Processing CHEMBL76241 in molecule.smi (178/4695). Average speed: 0.27 s/mol.
Processing CHEMBL431784 in molecule.smi (179/4695). Average speed: 0.27 s/mol.
Processing CHEMBL352500 in molecule.smi (181/4695). Average speed: 0.27 s/mol.
Processing CHEMBL51934 in molecule.smi (180/4695). Average speed: 0.27 s/mol.
Processing CHEMBL355740 in molecule.smi (183/4695). Average speed: 0.27 s/mol.
Processing CHEMBL292314 in molecule.smi (182/4695). Average speed: 0.27 s/mol.
Processing CHEMBL75919 in molecule.smi (185/4695). Average speed: 0.27 s/mol.
Processing CHEMBL54727 in molecule.smi (184/4695). Average speed: 0.27 s/mol.
Processing CHEMBL309351 in molecule.smi (186/4695). Average speed: 0.27 s/mol.
Processing CHEMBL75743 in molecule.smi (187/4695). Average speed: 0.27 s/mol.
Processing CHEMBL76135 in molecule.smi (188/4695). Average speed: 0.26 s/mol.
Processing CHEMBL440497 in molecule.smi (189/4695). Average speed: 0.26 s/mol.
Processing CHEMBL368196 in molecule.smi (190/4695). Average speed: 0.27 s/mol.
Processing CHEMBL62084 in molecule.smi (191/4695). Average speed: 0.27 s/mol.
Processing CHEMBL172118 in molecule.smi (192/4695). Average speed: 0.27 s/mol.
Processing CHEMBL1202875 in molecule.smi (193/4695). Average speed: 0.26 s/mol.
Processing CHEMBL436367 in molecule.smi (194/4695). Average speed: 0.26 s/mol.
Processing CHEMBL132365 in molecule.smi (195/4695). Average speed: 0.26 s/mol.
Processing CHEMBL3215535 in molecule.smi (196/4695). Average speed: 0.26 s/mol.
Processing CHEMBL1202865 in molecule.smi (197/4695). Average speed: 0.26 s/mol.
Processing CHEMBL133520 in molecule.smi (198/4695). Average speed: 0.26 s/mol.
Processing CHEMBL1202884 in molecule.smi (200/4695). Average speed: 0.26 s/mol.
Processing CHEMBL130373 in molecule.smi (199/4695). Average speed: 0.26 s/mol.
Processing CHEMBL263198 in molecule.smi (201/4695). Average speed: 0.26 s/mol.
Processing CHEMBL133906 in molecule.smi (202/4695). Average speed: 0.26 s/mol.
Processing CHEMBL134240 in molecule.smi (204/4695). Average speed: 0.26 s/mol.
Processing CHEMBL1204162 in molecule.smi (203/4695). Average speed: 0.26 s/mol.
Processing CHEMBL132030 in molecule.smi (205/4695). Average speed: 0.26 s/mol.
Processing CHEMBL133448 in molecule.smi (206/4695). Average speed: 0.26 s/mol.
Processing CHEMBL130880 in molecule.smi (207/4695). Average speed: 0.26 s/mol.
Processing CHEMBL1202874 in molecule.smi (208/4695). Average speed: 0.26 s/mol.
Processing CHEMBL133441 in molecule.smi (209/4695). Average speed: 0.26 s/mol.
Processing CHEMBL130427 in molecule.smi (210/4695). Average speed: 0.26 s/mol.
Processing CHEMBL132260 in molecule.smi (212/4695). Average speed: 0.26 s/mol.
Processing CHEMBL134154 in molecule.smi (211/4695). Average speed: 0.26 s/mol.
Processing CHEMBL1204296 in molecule.smi (214/4695). Average speed: 0.25 s/mol.
Processing CHEMBL1204299 in molecule.smi (213/4695). Average speed: 0.25 s/mol.
Processing CHEMBL1202885 in molecule.smi (215/4695). Average speed: 0.25 s/mol.
Processing CHEMBL337453 in molecule.smi (216/4695). Average speed: 0.25 s/mol.
Processing CHEMBL335922 in molecule.smi (217/4695). Average speed: 0.25 s/mol.
Processing CHEMBL132619 in molecule.smi (218/4695). Average speed: 0.25 s/mol.
Processing CHEMBL61515 in molecule.smi (220/4695). Average speed: 0.25 s/mol.
Processing CHEMBL293316 in molecule.smi (219/4695). Average speed: 0.25 s/mol.
Processing CHEMBL58034 in molecule.smi (222/4695). Average speed: 0.25 s/mol.
Processing CHEMBL442361 in molecule.smi (221/4695). Average speed: 0.25 s/mol.
Processing CHEMBL61965 in molecule.smi (223/4695). Average speed: 0.25 s/mol.
Processing CHEMBL62210 in molecule.smi (225/4695). Average speed: 0.25 s/mol.
Processing CHEMBL59790 in molecule.smi (224/4695). Average speed: 0.25 s/mol.
Processing CHEMBL57003 in molecule.smi (226/4695). Average speed: 0.25 s/mol.
Processing CHEMBL291783 in molecule.smi (227/4695). Average speed: 0.25 s/mol.
Processing CHEMBL294498 in molecule.smi (228/4695). Average speed: 0.25 s/mol.
Processing CHEMBL300170 in molecule.smi (229/4695). Average speed: 0.25 s/mol.
Processing CHEMBL61312 in molecule.smi (230/4695). Average speed: 0.25 s/mol.
Processing CHEMBL293268 in molecule.smi (231/4695). Average speed: 0.25 s/mol.
Processing CHEMBL293751 in molecule.smi (232/4695). Average speed: 0.25 s/mol.
Processing CHEMBL59192 in molecule.smi (233/4695). Average speed: 0.25 s/mol.
Processing CHEMBL300176 in molecule.smi (234/4695). Average speed: 0.25 s/mol.
Processing CHEMBL61905 in molecule.smi (235/4695). Average speed: 0.24 s/mol.
Processing CHEMBL58511 in molecule.smi (236/4695). Average speed: 0.24 s/mol.
Processing CHEMBL59074 in molecule.smi (237/4695). Average speed: 0.24 s/mol.
Processing CHEMBL294674 in molecule.smi (238/4695). Average speed: 0.24 s/mol.
Processing CHEMBL57842 in molecule.smi (239/4695). Average speed: 0.24 s/mol.
Processing CHEMBL60596 in molecule.smi (241/4695). Average speed: 0.24 s/mol.
Processing CHEMBL299898 in molecule.smi (240/4695). Average speed: 0.24 s/mol.
Processing CHEMBL60074 in molecule.smi (243/4695). Average speed: 0.24 s/mol.
Processing CHEMBL62031 in molecule.smi (242/4695). Average speed: 0.24 s/mol.
Processing CHEMBL59490 in molecule.smi (244/4695). Average speed: 0.24 s/mol.
Processing CHEMBL61180 in molecule.smi (245/4695). Average speed: 0.24 s/mol.
Processing CHEMBL60180 in molecule.smi (246/4695). Average speed: 0.24 s/mol.
Processing CHEMBL294152 in molecule.smi (247/4695). Average speed: 0.24 s/mol.
Processing CHEMBL294897 in molecule.smi (249/4695). Average speed: 0.24 s/mol.
Processing CHEMBL305386 in molecule.smi (248/4695). Average speed: 0.24 s/mol.
Processing CHEMBL60745 in molecule.smi (251/4695). Average speed: 0.24 s/mol.
Processing CHEMBL58190 in molecule.smi (250/4695). Average speed: 0.24 s/mol.
Processing CHEMBL58252 in molecule.smi (252/4695). Average speed: 0.24 s/mol.
Processing CHEMBL58194 in molecule.smi (253/4695). Average speed: 0.24 s/mol.
Processing CHEMBL294251 in molecule.smi (255/4695). Average speed: 0.24 s/mol.
Processing CHEMBL61126 in molecule.smi (254/4695). Average speed: 0.24 s/mol.
Processing CHEMBL60874 in molecule.smi (256/4695). Average speed: 0.24 s/mol.

In [ ]:
! ls -l

total 34296
-rw-r--r-- 1 root root   655414 Jun  9 17:00 acetylcholinesterase_04_bioactivity_data_3class_pIC50.csv
-rw-r--r-- 1 root root  8356701 Jun  9 17:08 descriptors_output.csv
drwxr-xr-x 3 root root     4096 Jun  9 17:00 __MACOSX
-rw-r--r-- 1 root root   310658 Jun  9 17:01 molecule.smi
drwxrwxr-x 4 root root     4096 May 30 10:10 PaDEL-Descriptor
-rw-r--r-- 1 root root      231 Jun  9 16:58 padel.sh
-rw-r--r-- 1 root root 25768637 Jun  9 16:58 padel.zip
drwxr-xr-x 1 root root     4096 May 29 18:19 sample_data

### **New version using pypadel**

In [ ]:
! wget https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip

--2026-06-07 17:25:18--  https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip [following]
--2026-06-07 17:25:18--  https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10871 (11K) [application/zip]
Saving to: ‘fingerprints_xml.zip’

fingerprints_xml.zi 100%[===================>]  10.62K  --.-KB/s    in 0s

2026-06-07 17:25:18 (103 MB/s) - ‘fingerprints_xml.zip’ saved [10871/10871]

In [ ]:
! unzip fingerprints_xml.zip

Archive:  fingerprints_xml.zip
  inflating: AtomPairs2DFingerprintCount.xml
  inflating: AtomPairs2DFingerprinter.xml
  inflating: EStateFingerprinter.xml
  inflating: ExtendedFingerprinter.xml
  inflating: Fingerprinter.xml
  inflating: GraphOnlyFingerprinter.xml
  inflating: KlekotaRothFingerprintCount.xml
  inflating: KlekotaRothFingerprinter.xml
  inflating: MACCSFingerprinter.xml
  inflating: PubchemFingerprinter.xml
  inflating: SubstructureFingerprintCount.xml
  inflating: SubstructureFingerprinter.xml

In [ ]:
from padelpy import padeldescriptor
padeldescriptor(
    mol_dir='./',
    d_file='descriptors_output.csv',
    fingerprints=True,
    descriptortypes='PubchemFingerprinter.xml',
    removesalt=True,
    standardizenitro=True,
    d_3d=False
)

## **Preparing the X and Y Data Matrices**

### **X data matrix**

In [ ]:
df3_X = pd.read_csv('descriptors_output.csv')

In [ ]:
df3_X

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL133897,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL336398,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL131588,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL130628,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL130478,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4690,CHEMBL4293155,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4691,CHEMBL4282558,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4692,CHEMBL4281727,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4693,CHEMBL4292349,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4694,CHEMBL4278260,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df3_X = df3_X.drop(columns=['Name'])
df3_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4690,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4691,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4692,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4693,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4694,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

## **Y variable**

### **Convert IC50 to pIC50**

In [ ]:
df3_Y = df3['pIC50']
df3_Y

0       6.124939
1       7.000000
2       4.301030
3       6.522879
4       6.096910
          ...
4690    5.612610
4691    5.595166
4692    5.419075
4693    5.460924
4694    5.555955
Name: pIC50, Length: 4695, dtype: float64

## **Combining X and Y variable**

In [ ]:
dataset3 = pd.concat([df3_X,df3_Y], axis=1)
dataset3

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.124939
1,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,7.000000
2,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,4.301030
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.522879
4,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,6.096910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4690,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.612610
4691,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.595166
4692,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.419075
4693,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.460924
4694,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,5.555955

In [ ]:
dataset3.to_csv('acetylcholinesterase_06_bioactivity_data_3class_pIC50_pubchem_fp.csv', index=False)

# **Let's download the CSV file to your local computer for the Part 3B (Model Building).**