<a href="https://colab.research.google.com/github/Sakhiur2022/QSAR-modeling-for-DHFR-TS/blob/main/notebooks/bioactivity_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Computational Drug Discovery [Part 1] Download Bioactivity Data**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

In [ ]:
! pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /usr/local/lib/python3.12/dist-packages (0.10.9)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.3.2)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.5.20)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.9.6)
Requirement already satisfied: url-normalize>=2.0 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (3.0.0)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)

## **Importing libraries**

In [ ]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for InhA Mycobacterium tuberculosis**

In [ ]:
# Target search for InhA Mycobacterium tuberculosis
target = new_client.target
target_query = target.search('InhA Mycobacterium tuberculosis').filter(target_type='single protein')
targets = pd.DataFrame.from_dict(target_query)
targets

Empty DataFrame
Columns: []
Index: []

### **Select and retrieve bioactivity data for *InhA* (seventh entry)**

We will assign the seventh entry (which corresponds to the target protein, *InhA*) to the ***selected_target*** variable

In [ ]:
selected_target = targets.target_chembl_id[6]
selected_target

'CHEMBL1849'

Here, we will retrieve only bioactivity data for *InhA* (CHEMBL1849) that are reported as IC$_{50}$ values in nM (nanomolar) unit.

In [ ]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [ ]:
df = pd.DataFrame.from_dict(res)

In [ ]:
df.head(3)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1774267,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,10.66
1,None,None,1774268,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,100.0
2,None,None,1774269,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,100.0

In [ ]:
df.standard_type.unique()

array(['IC50'], dtype=object)

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [ ]:
df.to_csv('bioactivity_data.csv', index=False)

## **Copying files to Google Drive**

Firstly, we need to mount the Google Drive into Colab so that we can have access to our Google adrive from within Colab.

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

Next, we create a **data** folder in our **Colab Notebooks** folder on Google Drive.

In [ ]:
! cp bioactivity_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [ ]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

total 286
-rw------- 1 root root 292732 May 31 06:49 bioactivity_data.csv

Let's see the CSV files that we have so far.

In [ ]:
! ls

bioactivity_data.csv  gdrive  sample_data

Taking a glimpse of the **bioactivity_data.csv** file that we've just created.

In [ ]:
! head bioactivity_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,modality,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,1774267,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,,,BAO_0000190,BAO_0000357,single protein format,O=C(Nc1ccccc1)C1CC(=O)N(C2CCCCC2)C1,,,CHEMBL1137386,J Med Chem,2006,"{'bei': '17.36', 'le': '0.32', 'lle': '2.16', 'sei': '10.06'}",,CHEMBL217926,,CHEMBL217926,4.97,0,http://www.openphacts.org/units/Nanomolar,606531,=,1,1,=,,IC50,nM,,10660.0,CHEMBL1849,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,,,IC50,uM,UO_0000065,,10.66
,,1774268,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,,,BAO_0000190,BAO_0000357,single protein format,O=C(Nc1ccccc1Br)C1CC(=O)N(C2CCCCC2)C1,,,CHEMBL1137386,J Med Chem,2006,,,CHEMBL216547,,CHEMBL216547,,0,http://www.openphacts.org/units/Nanomolar,606533,>,1,1,>,,IC50,nM,,100000.0,CHEMBL1849,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,,,IC50,uM,UO_0000065,,100.0
,,1774269,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,,,BAO_0000190,BAO_0000357,single protein format,O=C(Nc1ccc2c(c1)OCCO2)C1CC(=O)N(C2CCCCC2)C1,,,CHEMBL1137386,J Med Chem,2006,,,CHEMBL213720,,CHEMBL213720,,0,http://www.openphacts.org/units/Nanomolar,606567,>,1,1,>,,IC50,nM,,100000.0,CHEMBL1849,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,,,IC50,uM,UO_0000065,,100.0
,,1774270,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,,,BAO_0000190,BAO_0000357,single protein format,Cc1cccc(C)c1NC(=O)C1CC(=O)N(C2CCCCC2)C1,,,CHEMBL1137386,J Med Chem,2006,,,CHEMBL217274,,CHEMBL217274,,0,http://www.openphacts.org/units/Nanomolar,606554,>,1,1,>,,IC50,nM,,100000.0,CHEMBL1849,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,,,IC50,uM,UO_0000065,,100.0
,,1774271,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,,,BAO_0000190,BAO_0000357,single protein format,O=C(Nc1ccc(Oc2ccccc2)cc1)C1CC(=O)N(C2CCCCC2)C1,,,CHEMBL1137386,J Med Chem,2006,,,CHEMBL217773,,CHEMBL217773,,0,http://www.openphacts.org/units/Nanomolar,606549,>,1,1,>,,IC50,nM,,100000.0,CHEMBL1849,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,,,IC50,uM,UO_0000065,,100.0
,,1774272,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,,,BAO_0000190,BAO_0000357,single protein format,CCOc1ccc(NC(=O)C2CC(=O)N(C3CCCCC3)C2)cc1,,,CHEMBL1137386,J Med Chem,2006,,,CHEMBL217273,,CHEMBL217273,,0,http://www.openphacts.org/units/Nanomolar,606548,>,1,1,>,,IC50,nM,,100000.0,CHEMBL1849,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,,,IC50,uM,UO_0000065,,100.0
,,1774273,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,,,BAO_0000190,BAO_0000357,single protein format,CC(=O)Nc1cccc(NC(=O)C2CC(=O)N(C3CCCCC3)C2)c1,,,CHEMBL1137386,J Med Chem,2006,,,CHEMBL216781,,CHEMBL216781,,0,http://www.openphacts.org/units/Nanomolar,606543,>,1,1,>,,IC50,nM,,75000.0,CHEMBL1849,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,,,IC50,uM,UO_0000065,,75.0
,,1774274,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,,,BAO_0000190,BAO_0000357,single protein format,O=C(Nc1ccc(Cl)cc1)C1CC(=O)N(C2CCCCC2)C1,,,CHEMBL1137386,J Med Chem,2006,,,CHEMBL265016,,CHEMBL265016,,0,http://www.openphacts.org/units/Nanomolar,606537,>,1,1,>,,IC50,nM,,100000.0,CHEMBL1849,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,,,IC50,uM,UO_0000065,,100.0
,,1774275,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,,,BAO_0000190,BAO_0000357,single protein format,O=C(Nc1ccc(F)c(Cl)c1)C1CC(=O)N(C2CCCCC2)C1,,,CHEMBL1137386,J Med Chem,2006,"{'bei': '14.25', 'le': '0.29', 'lle': '1.23', 'sei': '9.77'}",,CHEMBL217524,,CHEMBL217524,4.83,0,http://www.openphacts.org/units/Nanomolar,606565,=,1,1,=,,IC50,nM,,14830.0,CHEMBL1849,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,,,IC50,uM,UO_0000065,,14.83

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [ ]:
df2 = df[df.standard_value.notna()]
df2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1774267,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,10.66
1,None,None,1774268,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,100.0
2,None,None,1774269,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,100.0
3,None,None,1774270,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,100.0
4,None,None,1774271,[],CHEMBL907779,Inhibition of Mycobacterium tuberculosis InhA,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26152821,[],CHEMBL5626588,Inhibition of his6-tagged Mycobacterium tuberc...,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,0.844
483,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26152822,[],CHEMBL5626588,Inhibition of his6-tagged Mycobacterium tuberc...,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,0.459
484,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26152823,[],CHEMBL5626588,Inhibition of his6-tagged Mycobacterium tuberc...,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,0.733
485,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26152824,[],CHEMBL5626588,Inhibition of his6-tagged Mycobacterium tuberc...,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,0.63
486,"{'action_type': 'INHIBITOR', 'description': 'N...",None,26152825,[],CHEMBL5626588,Inhibition of his6-tagged Mycobacterium tuberc...,B,None,None,BAO_0000190,...,Mycobacterium tuberculosis,Enoyl-[acyl-carrier-protein] reductase [NADH],1773,None,None,IC50,uM,UO_0000065,None,0.51

Apparently, for this dataset there is no missing data. But we can use the above code cell for bioactivity data of other target protein.

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [ ]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

### **Iterate the *molecule_chembl_id* to a list**

In [ ]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

### **Iterate *canonical_smiles* to a list**

In [ ]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

### **Iterate *standard_value* to a list**

In [ ]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

### **Combine the 4 lists into a dataframe**

In [ ]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

In [ ]:
df3

,molecule_chembl_id,canonical_smiles,bioactivity_class,standard_value
0,CHEMBL217926,O=C(Nc1ccccc1)C1CC(=O)N(C2CCCCC2)C1,inactive,10660.0
1,CHEMBL216547,O=C(Nc1ccccc1Br)C1CC(=O)N(C2CCCCC2)C1,inactive,100000.0
2,CHEMBL213720,O=C(Nc1ccc2c(c1)OCCO2)C1CC(=O)N(C2CCCCC2)C1,inactive,100000.0
3,CHEMBL217274,Cc1cccc(C)c1NC(=O)C1CC(=O)N(C2CCCCC2)C1,inactive,100000.0
4,CHEMBL217773,O=C(Nc1ccc(Oc2ccccc2)cc1)C1CC(=O)N(C2CCCCC2)C1,inactive,100000.0
...,...,...,...,...
452,CHEMBL5632618,O=C(NCc1cn(Cc2ccc(Oc3ccccc3)c(O)c2)nn1)c1cc2cc...,active,844.0
453,CHEMBL5633350,O=[N+]([O-])c1ccc(NCc2cn(Cc3ccc(Oc4ccccc4)c(O)...,active,459.0
454,CHEMBL5632202,CN(C)S(=O)(=O)c1ccc(NCc2cn(Cc3ccc(Oc4ccccc4)c(...,active,733.0
455,CHEMBL5634062,O=c1ccc2ccc(OCc3cnnn3Cc3ccc(Oc4ccccc4)c(O)c3)c...,active,630.0
456,CHEMBL5633965,Cc1cc(=O)oc2cc(OCc3cnnn3Cc3ccc(Oc4ccccc4)c(O)c...,active,510.0

### **Alternative method**

In [ ]:
selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
df3 = df2[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL217926,O=C(Nc1ccccc1)C1CC(=O)N(C2CCCCC2)C1,10660.0
1,CHEMBL216547,O=C(Nc1ccccc1Br)C1CC(=O)N(C2CCCCC2)C1,100000.0
2,CHEMBL213720,O=C(Nc1ccc2c(c1)OCCO2)C1CC(=O)N(C2CCCCC2)C1,100000.0
3,CHEMBL217274,Cc1cccc(C)c1NC(=O)C1CC(=O)N(C2CCCCC2)C1,100000.0
4,CHEMBL217773,O=C(Nc1ccc(Oc2ccccc2)cc1)C1CC(=O)N(C2CCCCC2)C1,100000.0
...,...,...,...
482,CHEMBL5632618,O=C(NCc1cn(Cc2ccc(Oc3ccccc3)c(O)c2)nn1)c1cc2cc...,844.0
483,CHEMBL5633350,O=[N+]([O-])c1ccc(NCc2cn(Cc3ccc(Oc4ccccc4)c(O)...,459.0
484,CHEMBL5632202,CN(C)S(=O)(=O)c1ccc(NCc2cn(Cc3ccc(Oc4ccccc4)c(...,733.0
485,CHEMBL5634062,O=c1ccc2ccc(OCc3cnnn3Cc3ccc(Oc4ccccc4)c(O)c3)c...,630.0
486,CHEMBL5633965,Cc1cc(=O)oc2cc(OCc3cnnn3Cc3ccc(Oc4ccccc4)c(O)c...,510.0

In [ ]:
pd.concat([df3,pd.Series(bioactivity_class)], axis=1)

,molecule_chembl_id,canonical_smiles,standard_value,0
0,CHEMBL217926,O=C(Nc1ccccc1)C1CC(=O)N(C2CCCCC2)C1,10660.0,inactive
1,CHEMBL216547,O=C(Nc1ccccc1Br)C1CC(=O)N(C2CCCCC2)C1,100000.0,inactive
2,CHEMBL213720,O=C(Nc1ccc2c(c1)OCCO2)C1CC(=O)N(C2CCCCC2)C1,100000.0,inactive
3,CHEMBL217274,Cc1cccc(C)c1NC(=O)C1CC(=O)N(C2CCCCC2)C1,100000.0,inactive
4,CHEMBL217773,O=C(Nc1ccc(Oc2ccccc2)cc1)C1CC(=O)N(C2CCCCC2)C1,100000.0,inactive
...,...,...,...,...
370,NaN,NaN,NaN,inactive
371,NaN,NaN,NaN,inactive
372,NaN,NaN,NaN,inactive
373,NaN,NaN,NaN,inactive
374,NaN,NaN,NaN,intermediate

Saves dataframe to CSV file

In [ ]:
df3.to_csv('bioactivity_preprocessed_data.csv', index=False)

In [ ]:
! ls -l

total 332
-rw-r--r-- 1 root root 292732 Jun  5 04:37 bioactivity_data.csv
-rw-r--r-- 1 root root  36618 Jun  5 04:44 bioactivity_preprocessed_data.csv
drwx------ 5 root root   4096 Jun  5 04:38 gdrive
drwxr-xr-x 1 root root   4096 May 26 13:25 sample_data

Let's copy to the Google Drive

In [ ]:
! cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [ ]:
! ls "/content/gdrive/My Drive/Colab Notebooks/data"

bioactivity_data.csv  bioactivity_preprocessed_data.csv

---